var goals={
  'H4X0R':`<h1>|-|4(|(3|)</h1>|_| 60+ |-|4(|(3|) |\\/|8`,
  'FAIL':`The Confederate States of America were not as successful as the Union with the telegraph because they had a smaller telegraph network and had limited supplies such as wires and battery acid.`,
  'RELAY':`<a href='http://w1tp.com/2582.jpg'><img src='http://w1tp.com/2582.jpg' alt='telegraph relay'></a>Henry came up with the concept of <em>electrical relay</em> to deal with the wire resisting the electric signal that had the distance the current would travel before it weakened calculated and a second circuit with a second battery would receive the signal and pass it on at full power.`,
  'MORSE':`<a href='https://content.artofmanliness.com/uploads/2008/10/morse-code.jpg'><img src='https://content.artofmanliness.com/uploads/2008/10/morse-code.jpg' alt='morse code reference table'></a>The Morse code, developed by Samuel Morse, uses sequences of short and long bursts of electricity to represent letters. Then a receiving pencil could draw the bursts of electricity on paper.`,
  'NEWS':`News of the secessions of states were submitted via the telegraph. The press competed for the latest updates, and the telegraph helped news spread quickly; it was useful for public support and troops relied on it as a source of information.`,
  'ORDERS':`The telegraph allowed military commanders to obtain intelligence, direct troops, and strategize quickly from a single command post across long distances, which was how the North won. Secretary of war Edwin McMasters Stanton and president Abraham Lincoln relied on it to monitor the fighting. The Union military started a telegraph system for themselves in October 1861, and generals connected their headquarters with the department of war office on November 1st, 1861. The telegraph also allowed quick responses to condition changes.`,
  'SPY':`Anyone could tap into telegraph wires and eavesdrop on messages and occasionally replace them with incorrect information, so people started ciphering messages. Both sides used ciphers to encode their messages.`
},
hearing={
  'POWER':`<a href='http://uploads.edubilla.com/inventions/39/38/electromagnetictelegraph2.png'><img src='http://uploads.edubilla.com/inventions/39/38/electromagnetictelegraph2.png' alt='electromagnetic telegraph'></a>William Sturgeon invented the telegraph, but Joseph Henry, the first secretary of the Smithsonian Institution, improved it in the late 1820s by increasing the power of the electromagnet. He did so by wrapping more wire around the iron core and insulating it with cloth, making it a hundred times more powerful.`,
  'COPYCAT':`<a href='https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Samuel_Morse_with_his_Recorder_by_Brady%2C_1857.png/275px-Samuel_Morse_with_his_Recorder_by_Brady%2C_1857.png'><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Samuel_Morse_with_his_Recorder_by_Brady%2C_1857.png/275px-Samuel_Morse_with_his_Recorder_by_Brady%2C_1857.png' alt='Samuel Morse'></a>Samuel Morse took over Henry’s work on the telegraph and patented it, though he did not credit Henry. He did, however, come up with Morse code.`,
  'CONNECT':`<a href='http://www.history.army.mil/books/30-17/notes/53.jpg'><img src='http://www.history.army.mil/books/30-17/notes/53.jpg' alt='US telegraph map'></a>By 1860, the United States had over fifty thousand miles of telegraph wire; Florida was the only state east of the Mississippi River without telegraph coverage. The Western Union Telegraph Company connected New York and San Francisco in October 1861 and the Pony Express ended two days later. By the end of the Civil War, 24 kilometers of telegraph lines were built just for the military.`,
  'LINCOLN':`The Department of War had a telegraph office, but the White House did not, so Lincoln was a common sight at the office to get informed.`,
  'WAGON':`<a href='https://i.kinja-img.com/gawker-media/image/upload/s--PRpQ-iPc--/c_scale,f_auto,fl_progressive,q_80,w_800/18bw9gbihsu8djpg.jpg'><img src='https://i.kinja-img.com/gawker-media/image/upload/s--PRpQ-iPc--/c_scale,f_auto,fl_progressive,q_80,w_800/18bw9gbihsu8djpg.jpg' alt='telegraph wagon'></a>Troops used telegraph battery wagons to communicate with commanders; the wagons had a hundred battery cups and wires wound in reels carried by mules with thirty operators and a few soldiers.`,
  'ROUTE':`The Union had more advanced ciphers and the general superintendent of the Western Union Telegraph Company developed a cipher called the <em>route cipher</em> that had words arranged on a grid and then a new message was created by following a different route on the grid. Null words were added and important words were substituted to result in what would be nonsense to any eavesdropper.`,
  'EASY':`The Confederates, however, had more simpler and easier to crack ciphers. <em>Dictionary code</em> had sets of numbers represent the location of each word in a dictionary, and <em>Caesar code</em> cycled the letters by a certain amount in the alphabet.`
};
